name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: Dizainer05
          svg_out_path: output/github-contribution-grid-snake-dark.svg
      - uses: EndBug/add-and-commit@v9
        with:
          message: "Update snake animation"